"""add enterprise social media schema

Revision ID: 7a178afae9d7
Revises: c5ed4493f8be
Create Date: 2026-07-15 14:53:26.926911
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7a178afae9d7'
down_revision: Union[str, Sequence[str], None] = 'c5ed4493f8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hashtags_name'), 'hashtags', ['name'], unique=True)
    op.create_table('content_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_reports_reason'), 'content_reports', ['reason'], unique=False)
    op.create_index(op.f('ix_content_reports_reporter_id'), 'content_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_content_reports_resource_id'), 'content_reports', ['resource_id'], unique=False)
    op.create_index(op.f('ix_content_reports_resource_type'), 'content_reports', ['resource_type'], unique=False)
    op.create_index(op.f('ix_content_reports_status'), 'content_reports', ['status'], unique=False)
    op.create_index('ix_content_reports_status_created', 'content_reports', ['status', 'created_at'], unique=False)
    op.create_table('follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('follower_id', sa.String(length=36), nullable=False),
    sa.Column('following_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow_edge')
    )
    op.create_index(op.f('ix_follows_follower_id'), 'follows', ['follower_id'], unique=False)
    op.create_index('ix_follows_following_created', 'follows', ['following_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_follows_following_id'), 'follows', ['following_id'], unique=False)
    op.create_table('friend_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=False),
    sa.Column('addressee_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friend_request_direction')
    )
    op.create_index(op.f('ix_friend_requests_addressee_id'), 'friend_requests', ['addressee_id'], unique=False)
    op.create_index('ix_friend_requests_addressee_status', 'friend_requests', ['addressee_id', 'status'], unique=False)
    op.create_index(op.f('ix_friend_requests_requester_id'), 'friend_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_status'), 'friend_requests', ['status'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_low_id', sa.String(length=36), nullable=False),
    sa.Column('user_high_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_high_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_low_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_low_id', 'user_high_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendships_user_high_id'), 'friendships', ['user_high_id'], unique=False)
    op.create_index(op.f('ix_friendships_user_low_id'), 'friendships', ['user_low_id'], unique=False)
    op.create_table('social_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('privacy', sa.String(length=20), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_groups_name'), 'social_groups', ['name'], unique=False)
    op.create_index(op.f('ix_social_groups_owner_id'), 'social_groups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_social_groups_privacy'), 'social_groups', ['privacy'], unique=False)
    op.create_index(op.f('ix_social_groups_slug'), 'social_groups', ['slug'], unique=True)
    op.create_index(op.f('ix_social_groups_status'), 'social_groups', ['status'], unique=False)
    op.create_table('social_pages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_pages_category'), 'social_pages', ['category'], unique=False)
    op.create_index(op.f('ix_social_pages_name'), 'social_pages', ['name'], unique=False)
    op.create_index(op.f('ix_social_pages_owner_id'), 'social_pages', ['owner_id'], unique=False)
    op.create_index(op.f('ix_social_pages_slug'), 'social_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_social_pages_status'), 'social_pages', ['status'], unique=False)
    op.create_table('social_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('cover_url', sa.String(length=1000), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_visibility', sa.String(length=20), nullable=False),
    sa.Column('message_permission', sa.String(length=20), nullable=False),
    sa.Column('friend_list_visibility', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('friend_count', sa.Integer(), nullable=False),
    sa.Column('post_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_social_profiles_is_verified'), 'social_profiles', ['is_verified'], unique=False)
    op.create_index(op.f('ix_social_profiles_profile_visibility'), 'social_profiles', ['profile_visibility'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('media_url', sa.String(length=1200), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1200), nullable=True),
    sa.Column('caption', sa.String(length=1000), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stories_author_expires', 'stories', ['author_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_stories_author_id'), 'stories', ['author_id'], unique=False)
    op.create_index(op.f('ix_stories_expires_at'), 'stories', ['expires_at'], unique=False)
    op.create_table('group_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['social_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_group_member')
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_status'), 'group_members', ['status'], unique=False)
    op.create_index(op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False)
    op.create_table('page_admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['social_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'user_id', name='uq_page_admin')
    )
    op.create_index(op.f('ix_page_admins_page_id'), 'page_admins', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_admins_user_id'), 'page_admins', ['user_id'], unique=False)
    op.create_table('page_follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['social_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'user_id', name='uq_page_follow')
    )
    op.create_index(op.f('ix_page_follows_page_id'), 'page_follows', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_follows_user_id'), 'page_follows', ['user_id'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('page_id', sa.String(length=36), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('shared_post_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('feeling', sa.String(length=100), nullable=True),
    sa.Column('reaction_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['social_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['social_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_post_id'], ['social_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_author_id'), 'social_posts', ['author_id'], unique=False)
    op.create_index('ix_social_posts_author_published', 'social_posts', ['author_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_social_posts_group_id'), 'social_posts', ['group_id'], unique=False)
    op.create_index('ix_social_posts_group_published', 'social_posts', ['group_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_social_posts_page_id'), 'social_posts', ['page_id'], unique=False)
    op.create_index('ix_social_posts_page_published', 'social_posts', ['page_id', 'published_at'], unique=False)
    op.create_index(op.f('ix_social_posts_published_at'), 'social_posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_social_posts_shared_post_id'), 'social_posts', ['shared_post_id'], unique=False)
    op.create_index(op.f('ix_social_posts_status'), 'social_posts', ['status'], unique=False)
    op.create_index('ix_social_posts_status_visibility', 'social_posts', ['status', 'visibility'], unique=False)
    op.create_index(op.f('ix_social_posts_visibility'), 'social_posts', ['visibility'], unique=False)
    op.create_table('story_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('story_id', sa.String(length=36), nullable=False),
    sa.Column('viewer_id', sa.String(length=36), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'viewer_id', name='uq_story_view')
    )
    op.create_index(op.f('ix_story_views_story_id'), 'story_views', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_views_viewer_id'), 'story_views', ['viewer_id'], unique=False)
    op.create_table('post_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reaction_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_comments_author_id'), 'post_comments', ['author_id'], unique=False)
    op.create_index('ix_post_comments_parent_created', 'post_comments', ['parent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_comments_parent_id'), 'post_comments', ['parent_id'], unique=False)
    op.create_index('ix_post_comments_post_created', 'post_comments', ['post_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_post_comments_post_id'), 'post_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_comments_status'), 'post_comments', ['status'], unique=False)
    op.create_table('post_hashtags',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('hashtag_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'hashtag_id', name='uq_post_hashtag')
    )
    op.create_index(op.f('ix_post_hashtags_hashtag_id'), 'post_hashtags', ['hashtag_id'], unique=False)
    op.create_index(op.f('ix_post_hashtags_post_id'), 'post_hashtags', ['post_id'], unique=False)
    op.create_table('post_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1200), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1200), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_media_post_id'), 'post_media', ['post_id'], unique=False)
    op.create_index('ix_post_media_post_order', 'post_media', ['post_id', 'sort_order'], unique=False)
    op.create_table('post_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_reaction_user')
    )
    op.create_index(op.f('ix_post_reactions_post_id'), 'post_reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_reactions_reaction'), 'post_reactions', ['reaction'], unique=False)
    op.create_index(op.f('ix_post_reactions_user_id'), 'post_reactions', ['user_id'], unique=False)
    op.create_table('saved_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('collection', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_saved_post_user')
    )
    op.create_index(op.f('ix_saved_posts_post_id'), 'saved_posts', ['post_id'], unique=False)
    op.create_index(op.f('ix_saved_posts_user_id'), 'saved_posts', ['user_id'], unique=False)
    op.create_table('comment_reactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reaction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_reaction_user')
    )
    op.create_index(op.f('ix_comment_reactions_comment_id'), 'comment_reactions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_reactions_user_id'), 'comment_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_reactions_user_id'), table_name='comment_reactions')
    op.drop_index(op.f('ix_comment_reactions_comment_id'), table_name='comment_reactions')
    op.drop_table('comment_reactions')
    op.drop_index(op.f('ix_saved_posts_user_id'), table_name='saved_posts')
    op.drop_index(op.f('ix_saved_posts_post_id'), table_name='saved_posts')
    op.drop_table('saved_posts')
    op.drop_index(op.f('ix_post_reactions_user_id'), table_name='post_reactions')
    op.drop_index(op.f('ix_post_reactions_reaction'), table_name='post_reactions')
    op.drop_index(op.f('ix_post_reactions_post_id'), table_name='post_reactions')
    op.drop_table('post_reactions')
    op.drop_index('ix_post_media_post_order', table_name='post_media')
    op.drop_index(op.f('ix_post_media_post_id'), table_name='post_media')
    op.drop_table('post_media')
    op.drop_index(op.f('ix_post_hashtags_post_id'), table_name='post_hashtags')
    op.drop_index(op.f('ix_post_hashtags_hashtag_id'), table_name='post_hashtags')
    op.drop_table('post_hashtags')
    op.drop_index(op.f('ix_post_comments_status'), table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_post_id'), table_name='post_comments')
    op.drop_index('ix_post_comments_post_created', table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_parent_id'), table_name='post_comments')
    op.drop_index('ix_post_comments_parent_created', table_name='post_comments')
    op.drop_index(op.f('ix_post_comments_author_id'), table_name='post_comments')
    op.drop_table('post_comments')
    op.drop_index(op.f('ix_story_views_viewer_id'), table_name='story_views')
    op.drop_index(op.f('ix_story_views_story_id'), table_name='story_views')
    op.drop_table('story_views')
    op.drop_index(op.f('ix_social_posts_visibility'), table_name='social_posts')
    op.drop_index('ix_social_posts_status_visibility', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_status'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_shared_post_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_published_at'), table_name='social_posts')
    op.drop_index('ix_social_posts_page_published', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_page_id'), table_name='social_posts')
    op.drop_index('ix_social_posts_group_published', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_group_id'), table_name='social_posts')
    op.drop_index('ix_social_posts_author_published', table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_author_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_page_follows_user_id'), table_name='page_follows')
    op.drop_index(op.f('ix_page_follows_page_id'), table_name='page_follows')
    op.drop_table('page_follows')
    op.drop_index(op.f('ix_page_admins_user_id'), table_name='page_admins')
    op.drop_index(op.f('ix_page_admins_page_id'), table_name='page_admins')
    op.drop_table('page_admins')
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_status'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_stories_expires_at'), table_name='stories')
    op.drop_index(op.f('ix_stories_author_id'), table_name='stories')
    op.drop_index('ix_stories_author_expires', table_name='stories')
    op.drop_table('stories')
    op.drop_index(op.f('ix_social_profiles_profile_visibility'), table_name='social_profiles')
    op.drop_index(op.f('ix_social_profiles_is_verified'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index(op.f('ix_social_pages_status'), table_name='social_pages')
    op.drop_index(op.f('ix_social_pages_slug'), table_name='social_pages')
    op.drop_index(op.f('ix_social_pages_owner_id'), table_name='social_pages')
    op.drop_index(op.f('ix_social_pages_name'), table_name='social_pages')
    op.drop_index(op.f('ix_social_pages_category'), table_name='social_pages')
    op.drop_table('social_pages')
    op.drop_index(op.f('ix_social_groups_status'), table_name='social_groups')
    op.drop_index(op.f('ix_social_groups_slug'), table_name='social_groups')
    op.drop_index(op.f('ix_social_groups_privacy'), table_name='social_groups')
    op.drop_index(op.f('ix_social_groups_owner_id'), table_name='social_groups')
    op.drop_index(op.f('ix_social_groups_name'), table_name='social_groups')
    op.drop_table('social_groups')
    op.drop_index(op.f('ix_friendships_user_low_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_user_high_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_status'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_requester_id'), table_name='friend_requests')
    op.drop_index('ix_friend_requests_addressee_status', table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_addressee_id'), table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index(op.f('ix_follows_following_id'), table_name='follows')
    op.drop_index('ix_follows_following_created', table_name='follows')
    op.drop_index(op.f('ix_follows_follower_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index('ix_content_reports_status_created', table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_status'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_resource_type'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_resource_id'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_reporter_id'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_reason'), table_name='content_reports')
    op.drop_table('content_reports')
    op.drop_index(op.f('ix_hashtags_name'), table_name='hashtags')
    op.drop_table('hashtags')
    # ### end Alembic commands ###
